### ISSUE TITLE
No error is thrown when target transformer is not found

### ISSUE THREAD

**Issue by gajus** [gaearon/babel-plugin-react-transform#4]
`.babelrc`:

```json
{
    "stage": 0,
    "plugins": [
        "react-transform"
    ],
    "extra": {
        "react-transform": [
            {
                "target": "does-not-exist"
            }
        ]
    }
}
```

**Comment by gajus** [comment]
I can confirm that babel config is being loaded, e.g.

```
ERROR in ./src/index.js
Module build failed: ReferenceError: Unknown plugin "react-transform2"
    at PluginManager.subnormaliseString (/Users/gajus/Documents/dev/gajus/babel-react-css-modules-test/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/plugin-manager.js:147:13)
    at PluginManager.add (/Users/gajus/Documents/dev/gajus/babel-react-css-modules-test/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/plugin-manager.js:190:40)
    at File.buildTransformers (/Users/gajus/Documents/dev/gajus/babel-react-css-modules-test/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/gajus/Documents/dev/gajus/babel-react-css-modules-test/node_modules/babel-loader/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/gajus/Documents/dev/gajus/babel-react-css-modules-test/node_modules/babel-loader/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/gajus/Documents/dev/gajus/babel-react-css-modules-test/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/gajus/Documents/dev/gajus/babel-react-css-modules-test/node_modules/babel-loader/index.js:69:12)
 @ multi app
```

**Comment by gaearon** [comment]
We should add more error handling. PRs are welcome.

**Comment by gaearon** [comment]
Personally I don’t plan to work on this so closing.
Improvements as PRs are still welcome.
