### ISSUE TITLE
Fails when running mocha

### ISSUE THREAD

**Issue by nschurmann** [gaearon/babel-plugin-react-transform#44]
Hey guys, i get the following error when trying to run mocha:
`````````
/Users/nicolas/Sites/webpack-tuto/node_modules/babel-plugin-react-transform/lib/index.js:258
  return new Plugin('babel-plugin-react-transform', {
         ^
TypeError: undefined is not a function
    at exports.default (/Users/nicolas/Sites/webpack-tuto/node_modules/babel-plugin-react-transform/lib/index.js:258:10)
    at Function.memoisePluginContainer (/Users/nicolas/Sites/webpack-tuto/node_modules/mocha-babel/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:46:23)
    at PluginManager.add (/Users/nicolas/Sites/webpack-tuto/node_modules/mocha-babel/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/plugin-manager.js:130:30)
    at File.buildTransformers (/Users/nicolas/Sites/webpack-tuto/node_modules/mocha-babel/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:281:21)
    at new File (/Users/nicolas/Sites/webpack-tuto/node_modules/mocha-babel/node_modules/babel/node_modules/babel-core/lib/babel/transformation/file/index.js:148:10)
    at TransformerPipeline.transform (/Users/nicolas/Sites/webpack-tuto/node_modules/mocha-babel/node_modules/babel/node_modules/babel-core/lib/babel/transformation/transformer-pipeline.js:87:16)
    at Object.transformFileSync (/Users/nicolas/Sites/webpack-tuto/node_modules/mocha-babel/node_modules/babel/node_modules/babel-core/lib/babel/api/node.js:108:42)
    at compile (/Users/nicolas/Sites/webpack-tuto/node_modules/mocha-babel/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:101:20)
    at normalLoader (/Users/nicolas/Sites/webpack-tuto/node_modules/mocha-babel/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:150:14)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/nicolas/Sites/webpack-tuto/node_modules/mocha-babel/node_modules/babel/node_modules/babel-core/lib/babel/api/register/node.js:163:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /usr/local/lib/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/usr/local/lib/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/usr/local/lib/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
`````````

Seems to fail, does anybody have mocha running with this?

**Comment by gaearon** [comment]
Either way, you are intended the run Mocha with this transform enabled.
Run Mocha with a different `NODE_ENV` so that this plugin is not active.

**Comment by nschurmann** [comment]
Solved it changing how mocha is executed:

`mocha spec/**/*.js --compilers js:babel/register -R spec -w`

Instead of calling mocha-babel
