### ISSUE TITLE
Unknown option: base.extra with Babel 6

### ISSUE THREAD

**Issue by carloscuatin** [gaearon/babel-plugin-react-transform#59]
error with babel-loader
how to use babel-plugin-react-transform ??
```
ERROR in ./src/templates/azul/app.js
Module build failed: ReferenceError: [BABEL] /Users/carlos/www/mall4g-templates/src/templates/azul/app.js: Unknown option: base.extra
    at Logger.error (/Users/carlos/www/mall4g-templates/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/carlos/www/mall4g-templates/node_modules/babel-core/lib/transformation/file/options/option-manager.js:262:18)
    at OptionManager.init (/Users/carlos/www/mall4g-templates/node_modules/babel-core/lib/transformation/file/options/option-manager.js:416:10)
    at File.initOptions (/Users/carlos/www/mall4g-templates/node_modules/babel-core/lib/transformation/file/index.js:190:75)
    at new File (/Users/carlos/www/mall4g-templates/node_modules/babel-core/lib/transformation/file/index.js:121:22)
    at Pipeline.transform (/Users/carlos/www/mall4g-templates/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transpile (/Users/carlos/www/mall4g-templates/node_modules/babel-loader/index.js:14:22)
    at Object.module.exports (/Users/carlos/www/mall4g-templates/node_modules/babel-loader/index.js:87:14)
```

**Comment by nkbt** [comment]
Do you use beta version 2.0.0?
```
npm install --save-dev babel-plugin-react-transform@beta
```

Current stable 1.1 is babel5 and not babel6 compatible.

**Comment by kpdecker** [comment]
I am seeing the same, using
```
 ├── babel-plugin-react-transform@2.0.0-beta1
```

**Comment by kpdecker** [comment]
For anyone who runs upon this in the future:
I had to remove the webpack configuration parameters and move this to the babel config proper. After doing this, everything appears to be working again.
https://github.com/kpdecker/linoleum-webpack/commit/e4f9e31a1ffffd27f5e595485d1ea2e88e91ae5a

**Comment by nkbt** [comment]
Ah I'm using `.babelrc` so could not reproduce.
Also when you pass params to the loader in webpack it is ok to `JSON.stringify` it. Try it if you keen, that might work.

**Comment by carloscuatin** [comment]
yes, i am use beta version 2.0.0

**Comment by thejameskyle** [comment]
Your `.babelrc` file has an invalid option `extra`. This option was taken away in Babel 6 in favor of plugin specific options.

**Comment by carloscuatin** [comment]
how to config webpack with babel-plugin-react-transform, in app with server side renderin ?

**Comment by arhcstolen** [comment]
In your webpack config, when you specify the babel-loader object, add a ```query``` property, which will contain the plugin configuration.

It should be something like [this](https://github.com/arhcstolen/my-react-boilerplate/blob/master/webpack.config.development.babel.js#L42).

**Comment by carloscuatin** [comment]
thanks @arhcstolen  (y)
