### ISSUE TITLE
Display name cannot be resolved in all cases

### ISSUE THREAD

**Issue by Nickman87** [gaearon/babel-plugin-react-transform#61]
I have the following component:

```javascript
define(['react',
        'snappy',
        'drool/viewport/templates/viewport',
        'navigation',
        'viewfactory'
    ],
    function(React, Snappy, Viewport, Navigation, viewfactory) {

        return React.createClass(viewfactory.create({

            displayName: 'App',

            propTypes: {
                activeMenu: React.PropTypes.array,
                subNav: React.PropTypes.array
            },

            mixins: [Snappy.Routing.Navigation],

            render: function () {
                var navigation = <Navigation path={this.getPath()}
                                             centerItem={this.props.activeMenu ? this.props.activeMenu[0] : undefined}
                                             subNav={this.props.subNav ? this.props.subNav[0] : undefined} />;

                return (
                    <Viewport navigation={navigation}>
                        {this.props.children}
                    </Viewport>
                );

            }
        }));

    });
```

and when transforming I receive the following error:
```
ERROR in ../frontend/src/js/views/app.jsx
Module build failed: TypeError: e:/Code/PronetSquared/frontend/src/js/views/app.jsx: Cannot read property 'find' of undefined
    at find (e:\Code\PronetSquared\frontend\node_modules\array-find\find.js:5:17)
    at getDisplayName (e:\Code\PronetSquared\frontend\node_modules\babel-plugin-react-transform\lib\index.js:33:41)
    at Object.CallExpression (e:\Code\PronetSquared\frontend\node_modules\babel-plugin-react-transform\lib\index.js:110:22)
    at NodePath._call (e:\Code\PronetSquared\frontend\node_modules\babel-traverse\lib\path\context.js:74:18)
    at NodePath.call (e:\Code\PronetSquared\frontend\node_modules\babel-traverse\lib\path\context.js:46:17)
    at NodePath.visit (e:\Code\PronetSquared\frontend\node_modules\babel-traverse\lib\path\context.js:104:12)
    at TraversalContext.visitQueue (e:\Code\PronetSquared\frontend\node_modules\babel-traverse\lib\context.js:153:16)
    at TraversalContext.visitSingle (e:\Code\PronetSquared\frontend\node_modules\babel-traverse\lib\context.js:113:19)
    at TraversalContext.visit (e:\Code\PronetSquared\frontend\node_modules\babel-traverse\lib\context.js:197:19)
    at Function.traverse.node (e:\Code\PronetSquared\frontend\node_modules\babel-traverse\lib\index.js:139:17)
 @ ../frontend/src/js/router.jsx 51:0-98:2
```

This results in an error in the getDisplayName method on the first line (when looking for the actual property)
```javascript
  function getDisplayName(node) {
	var property = (0, _arrayFind2.default)(node.arguments[0].properties, function (node) {
		return node.key.name === 'displayName';
	});
    return property && property.value.value;
  }
```

Is this related to the viewfactory wrapper we have in place?

**Comment by gaearon** [comment]
I don't think we want to support this pattern (`React.createClass(viewfactory.create({}))`) but we shouldn't crash either.

**Comment by frekw** [comment]
I'm seeing the same error for the following example as well:

```javascript
export const HOFC = spec => {
  spec.propTypes = {
    onFoo: PropTypes.func,
  }

  return React.createClass(spec)
}
```

**Comment by toddwildey** [comment]
+1 for solving this - I'm having this issue also.

**Comment by gaearon** [comment]
2.0.1 and more recent versions no longer crash in this case.
We can’t “guess” and extract `displayName` in this case but we won’t crash so I’m closing.
