### ISSUE TITLE
Module build failed: TypeError: template is not a function

### ISSUE THREAD

**Issue by jancassio** [gaearon/babel-plugin-react-transform#68]
Hi,

I had started a simple project using webpack and I'm getting the error below:

```shell
ERROR in ./app/index.jsx
Module build failed: TypeError: template is not a function
    at exports.default (/Users/jancassio/Works/labs/webpack/kanban-app/node_modules/babel-plugin-react-transform/lib/index.js:60:33)
    at Function.memoisePluginContainer (/Users/jancassio/Works/labs/webpack/kanban-app/node_modules/babel-core/lib/transformation/file/plugin-manager.js:77:23)
    at PluginManager.add (/Users/jancassio/Works/labs/webpack/kanban-app/node_modules/babel-core/lib/transformation/file/plugin-manager.js:209:30)
    at File.buildTransformers (/Users/jancassio/Works/labs/webpack/kanban-app/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/jancassio/Works/labs/webpack/kanban-app/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/jancassio/Works/labs/webpack/kanban-app/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at transpile (/Users/jancassio/Works/labs/webpack/kanban-app/node_modules/babel-loader/index.js:12:22)
    at Object.module.exports (/Users/jancassio/Works/labs/webpack/kanban-app/node_modules/babel-loader/index.js:71:12)
 @ multi main
```

I don't have any clue about how to fix this issue, I tried to remove entire `node_modules` and install all modules again but still the same.

If necessary, I can share some source. 
Any ideas about how to fix are welcome.

Thanks.

**Comment by jancassio** [comment]
Not sure if this info can be helpful but `"babel-plugin-react-transform": "^1.1.1"` still working fine, this looks like a problem at version `2.0.0`.

**Comment by danmartinez101** [comment]
Can you share the output of `npm outdated`?

Specifically, are you using babel@6?

**Comment by jancassio** [comment]
Sure thing, there is:

```shell
Package       Current  Wanted  Latest  Location
babel-loader    5.4.0   5.4.0   6.2.0  wherever
```

I'm using `babel-loader@5.x`.

**Comment by danmartinez101** [comment]
I suspect that if you upgrade that dependency, this error will go away. The 2.0 release was mainly a rewrite to become compatible with babel@6.

It might make sense for babel@>5 to be added to package.json as a peerDependency so that npm at least warns about the incompatibility. I'm not 100% what the impact of peerDeps are in npm@2 though.

**Comment by gaearon** [comment]
From the first line in README:

>These docs are for the v2 release using Babel 6, if you are still on Babel 5 then you should use v1.1 instead.

;-)

I'm not sure how peerdeping on babel-loader would work with presets. Namely would presets be forced to also install it with npm@2.x? That would be weird. I think we'll avoid peerdep and just refer people to this issue.

**Comment by jancassio** [comment]
Yeah makes sense, right now the babel6.x isn't a big deal so the version v1.1 fits perfectly.

@gaearon since you guys made a whole refactor to make the plugin compatible with Babel 6, I guess is much better to developer webpack config to be compatible with Babel 6 instead to get headache with peer dependencies.

From [Babel 6 release post](http://babeljs.io/blog/2015/10/29/6.0.0/):

> When updating your plugins, please remember to bump your major versions since this makes Babel 5 and 6 incompatible. Semver is important!

Thanks guys.
