### ISSUE TITLE
arguments[0] is Function

### ISSUE THREAD

**Issue by jsers** [gaearon/babel-plugin-react-transform#71]
https://github.com/gaearon/babel-plugin-react-transform/blob/master/src/index.js#L36

```
Module build failed: TypeError: /Users/xxx/bable-react/react-transform-boilerplate/src/App.js: Cannot read property 'find' of undefined
    at find (/Users/daixiaqing/git/src/bable-react/react-transform-boilerplate/node_modules/array-find/find.js:5:17)
    at getDisplayName (/Users/daixiaqing/git/src/bable-react/react-transform-boilerplate/node_modules/babel-plugin-react-transform/lib/index.js:33:44)
    at Object.CallExpression (/Users/daixiaqing/git/src/bable-react/react-transform-boilerplate/node_modules/babel-plugin-react-transform/lib/index.js:110:27)
    at NodePath._call (/Users/daixiaqing/git/src/bable-react/react-transform-boilerplate/node_modules/babel-traverse/lib/path/context.js:74:18)
    at NodePath.call (/Users/daixiaqing/git/src/bable-react/react-transform-boilerplate/node_modules/babel-traverse/lib/path/context.js:46:17)
    at NodePath.visit (/Users/daixiaqing/git/src/bable-react/react-transform-boilerplate/node_modules/babel-traverse/lib/path/context.js:104:12)
    at TraversalContext.visitQueue (/Users/daixiaqing/git/src/bable-react/react-transform-boilerplate/node_modules/babel-traverse/lib/context.js:153:16)
    at TraversalContext.visitSingle (/Users/daixiaqing/git/src/bable-react/react-transform-boilerplate/node_modules/babel-traverse/lib/context.js:113:19)
    at TraversalContext.visit (/Users/daixiaqing/git/src/bable-react/react-transform-boilerplate/node_modules/babel-traverse/lib/context.js:197:19)
    at Function.traverse.node (/Users/daixiaqing/git/src/bable-react/react-transform-boilerplate/node_modules/babel-traverse/lib/index.js:139:17)
```

update:
`React.createClass(fn())`

**Comment by jsers** [comment]
sorry 
https://github.com/gaearon/babel-plugin-react-transform/issues/61
